name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  node:
    uses: CosmicBytez/.github/.github/workflows/ci-node.yml@v1
    with:
      node-version: "22"
      runs-on: ubuntu-latest
      cache: npm
      type-check-command: npx tsc --noEmit
      test-command: npm test -- --coverage --ci
